### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by christophkoch** [epfldata/squall#23]
Nobody can use Squall as long as it has no license.

**Comment by avitorovic** [comment]
Released under Apache v2.0. Fixed.

**Comment by ElSeidy** [comment]
Alex, it still needs a discussion with Christoph.

**Comment by avitorovic** [comment]
It existed before, I don't know why it disappeared. It was Christoph who decided (long time ago) that the license should be Apache v2.0.

**Comment by ElSeidy** [comment]
@avitorovic , I removed it 30 mins ago. It was because Christoph asked me and asked to speak about this tomorrow.

**Comment by ElSeidy** [comment]
:+1:  from the airport!
