### ISSUE TITLE
coding error？

### ISSUE THREAD

**Issue by longjianzhiyun** [epfldata/squall#40]
Ifind an error from squall-core project,
source code file : [MyUtilities.java ](https://github.com/epfldata/squall/blob/master/squall-core/src/main/java/ch/epfl/data/squall/utilities/MyUtilities.java)，
line number 1162，`Type wrapper = veList.get(0).getType();
	for (int i = 1; i < veList.size(); i++) {
	    **final Type currentType = veList.get(1).getType();**
	    if (isDominant(currentType, wrapper))
		wrapper = currentType;
	}
	return wrapper;
    }`，the right code should be `final Type currentType = veList.get(i).getType();`

**Comment by avitorovic** [comment]
Good catch! Thanks for letting us know! Fixed.
